trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - README.md

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'DiceRoller.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  BotConfig.Token: '$(discord-token)'

steps:

# Build
- script: dotnet build -c $(buildConfiguration)
  displayName: 'Build'

# Test
- script: dotnet test -c $(buildConfiguration) --no-build
  displayName: 'Test'

#Publish
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'DiceRollerCmd/DiceRollerCmd.csproj'
    modifyOutputPath: false

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'DiceRoller-Net'
    publishLocation: 'Container'