trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - README.md

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'DiceRoller.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  BotConfig.Token: '$(discord-token)'

steps:

# Build
- script: dotnet build -c $(buildConfiguration)
  displayName: 'Build'

# Test
- script: dotnet test -c $(buildConfiguration) --no-build
  displayName: 'Test'

#Publish
- script: dotnet publish 'DiceRollerCmd/DiceRollerCmd.csproj' -o '$(Build.ArtifactStagingDirectory)' -c $(buildConfiguration) --no-build
  displayName: 'Publish'
