using System.Collections.Generic;

namespace DiceRoller.DragonQuest
{
    public class GrievousInjuries : LookupTable
    {
        public GrievousInjuries()
        {
            Map = new Dictionary<int, string>
            {
                { 5, "Congratulations! It’s a bleeder in your primary arm! Take __1 Damage Point__ from Endurance immediately and __1__ per pulse thereafter until the flow is staunched by a Healer of Rank 0 or above or you die" },
                { 7, "Oh no! Your opponent’s weapon has entered your secondary arm’s elbow joint and the tip has broken off. Take __2 Damage Points__ immediately from Endurance and that arm is useless until the sliver has been removed by a Healer of Rank 3 or above. Also, increase the chance of infection by __30__." },
                { 8, "A vicious puncture wound in your groin! Take __3 Damage Points__ immediately from Endurance and reduce your __TMR by 2__ until fully recovered, which will take two months. In addition, add __30__ to your chance of being infected (assuming you live long enough for such things to matter)." },
                { 10, "You have been stabbed in your secondary arm. Drop whatever you were holding in it and take __2 Damage Points__ immediately from Endurance. It will take a full week for the arm to be of any use to you whatsoever." },
                { 11, "Your aorta is severed and you are quite dead. Rest assured your companions will do their best to console your widow(er)." },
                { 12, "A stomach puncture. Nasty. You suffer __3 Damage Points__ immediately from Endurance and lose __2 from your TMR__ until fully recovered, which will take two months. Also, you are automatically __stunned__ for the next pulse (if you aren’t already), after which you may recover. Add __20__ to the chance to be infected." },
                { 13, "Your opponent’s weapon has entered your eye. Roll __D10__. On a roll of __1__, the weapon has entered your brain and you are dead. On a roll of __2–5__, your left eye is blinded. On a roll of __6–10__, your right eye is blinded. If you are lucky enough to be blinded instead of killed, you have suffered __2 Damage Points__ to Endurance. In addition, a figure who is blind in one eye suffers the following subtractions: __-1 from MD, -2 from PB, -4 from Perception__. A figure blinded in one eye reduces their base chance with any missile or thrown weapon by __30__." },
                { 18, "Tsk, tsk. A wound of the solid viscera. Usually fatal. Take __3 Damage Points__ to Endurance immediately and __1 per pulse__ thereafter until the bleeding is stopped by a Healer of Rank 2 or above or you die. Add __30__ to the chance of infection." },
                { 20, "Take a stab in the leg (your choice as to which one) resulting in a deep puncture of the thigh muscle. Suffer __1 Damage Point__ to Endurance immediately and reduce your __TMR by 1__ until you heal, which will take 4 weeks." },
                { 25, "A chest wound. Take __2 Damage Points__ to Endurance immediately and reduce your __TMR by 1__ until recovered (about 2 months). Look on the bright side, though. Your attacker’s weapon is caught in your rib cage and has been wrenched from their grasp." },
                { 27, "Bad luck! Your secondary hand has been severed at the wrist. Take __2 Damage Points__ to Endurance immediately and __1 point per pulse__ from Fatigue thereafter (Endurance when Fatigue is exhausted) until you are dead or the bleeding is staunched by a Healer of Rank 0 or above. If you live, reduce your __MD by 2__." },
                { 30, "Worst luck! Your primary hand has been severed. Take __2 Damage Points__ to Endurance immediately and __1 point per pulse__ from Fatigue thereafter (Endurance when Fatigue is exhausted) until you are dead or the bleeding is staunched by a Healer of Rank 0 or above. If you live, reduce your __MD by 2__." },
                { 34, "A minor wound. Your face is slashed open, ruining your boyish good looks and causing blood to spurt into your eyes. Reduce your __PB by 4__ permanently." },
                { 35, "Your secondary arm is sliced off at the shoulder. Take __5 Damage Points__ immediately from Endurance and __1 per pulse__ thereafter from Fatigue (Endurance when Fatigue is exhausted) until you are dead or the bleeding is staunched by a Healer of Rank 1 or above. Reduce your __MD by 2__ and your __AG by 1__." },
                { 36, "Your primary arm is sliced off at the shoulder. Take __5 Damage Points__ immediately from Endurance and __1 per pulse__thereafter from Fatigue (Endurance when Fatigue is exhausted) until you are dead or the bleeding is staunched by a Healer of Rank 1 or above. Reduce your __MD by 2__ and your __AG by 1__." },
                { 40, "You have been eviscerated! Take __4 Damage Points__ immediately from Endurance and __1 per pulse__ from Fatigue thereafter (Endurance when Fatigue is exhausted) until you are unconscious. Increase your chance of infection by __40__." },
                { 42, "A glancing blow lays open your scalp and severs one ear (your choice as to which one). Take __2 Damage Points__ immediately from Endurance. Reduce your __Perception by 2__." },
                { 43, "A savage slash rips open your cheek and jaw. Take an automatic __pass action__ next pulse due to the shock of the blow. Your __PB is increased by 1__, since your disfigurement will bring out the maternal/paternal instincts in the opposite gender." },
                { 50, "A slash along one arm, and it’s a bleeder! Take __2 Damage Points immediately__ from Endurance and lose __1 per pulse__ from Fatigue (Endurance when Fatigue is exhausted) until the bleeding is stopped by a Healer of Rank 1 or above or you die." },
                { 52, "Hamstrung! Roll __D10__. On a roll of __1–4__, it is your left leg. On a roll of __5–10__ it is your right. Take __4 Damage Points__ immediately from Endurance and __fall prone__. You may not stand unassisted until the wound is healed (which should take three months). Reduce your __AG by 3 permanently__." },
                { 60, "Your primary arm is crippled by a wicked slash! Take __2 damage Points__ immediately to Endurance and drop anything you have in your primary hand. The arm is unusable until healed, which should take 2 months." },
                { 67, "Your secondary arm is crippled! Take __2 damage Points__ immediately to Endurance and drop anything you have in your primary hand. The arm is unusable until healed, which should take 2 months." },
                { 69, "A nasty slash in the region of the shoulder and neck. Roll __D10__. On a roll of __1–3__, your head is severed and your corpse tumbles to the ground. On a roll of __4–6__, your secondary collar bone is crushed; on a roll of __7–10__ your primary collar bone is crushed. If your collar bone is crushed, the results are identical to 53–60, except you suffer __4 Damage Points__ to Endurance." },
                { 74, "A crushing blow smashes your helmet and causes a concussion. Take __3 Damage Points__ from Endurance and suffer a reduction of __4 in both MD and AG__ lasting for 3 days." },
                { 80, "A massive chest wound accompanied by broken ribs and crushed tissues. Very ugly, this. Take __5 Damage Points__ immediately from Endurance. Reduce your __MD and AG by 3__ each until this wound heals (which should take about 4 months). Increase your chance of infection by __10__." },
                { 84, "A crushing blow smashes tissue and produces internal injuries. You suffer __2 Damage Points__ immediately to Endurance and __1 per pulse__ thereafter to Fatigue (Endurance when Fatigue is exhausted) until unconscious or you receive the attention of a Healer of Rank 2 or above." },
                { 87, "A jarring blow to your primary shoulder inflicts __2 Damage Points__ immediately to Endurance. Roll __D10__; the result is the number of pulses the arm is useless. You immediately drop anything held in that hand." },
                { 89, "A jarring blow to your secondary shoulder inflicts __2 Damage Points__ immediately to Endurance. Roll __D10__; the result is the number of pulses the arm is useless. You immediately drop anything held in that hand." },
                { 92, "Your right hip is smashed horribly. Take __5 Damage Points__ immediately to Endurance and fall prone. You will be unable to walk until the damage has healed (which should take about 6 months). Good fun. When healed, you will still have a limp which will reduce your __TMR by 1 and your AG by 2__." },
                { 94, "Your left hip is smashed horribly. Take __5 Damage Points__ immediately to Endurance and fall prone. You will be unable to walk until the damage has healed (which should take about 6 months). Good fun. When healed, you will still have a limp which will reduce your __TMR by 1 and your AG by 2__." },
                { 97, "Your opponent’s weapon has come crashing down on your head and fractured your skull. You fall prone and are unconscious, and take __8 Damage Points__ to Endurance. If you survive, you lose __2 from AG, 2 from MD and 2 from Perception__. It will take a year in bed to recover." },
                { 100, "Crushing blow to your pelvis breaks bone and tears tissue. Take __7 Damage Points__ immediately to Endurance and fall prone. Make a __WP__ check to avoid falling unconscious. If you survive, you will be unable to move for __D10__ months." },
            };
        }
    }
}
